[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://intranet-api-er9d.onrender.com/api/v1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
