[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_API_URL = "https://intranet-api-er9d.onrender.com/api/v1"

[[redirects]]
  from = "/:deptId/docs"
  to = "/placeholder/docs"
  status = 200

[[redirects]]
  from = "/:deptId/review"
  to = "/placeholder/review"
  status = 200

[[redirects]]
  from = "/:deptId/upload"
  to = "/placeholder/upload"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
